export default {
  bridal_bouquet: [
    { src: '/bridal_bouquet/1.JPG', isStraight: false },
    { src: '/bridal_bouquet/2.JPG', isStraight: false },
    { src: '/bridal_bouquet/3.JPG', isStraight: false },
    { src: '/bridal_bouquet/4.JPG', isStraight: false },
    { src: '/bridal_bouquet/5.JPG', isStraight: false },
    { src: '/bridal_bouquet/6.JPG', isStraight: false },
    { src: '/bridal_bouquet/7.JPG', isStraight: false },
    { src: '/bridal_bouquet/8.JPG', isStraight: false },
    { src: '/bridal_bouquet/9.JPG', isStraight: false },
    { src: '/bridal_bouquet/10.JPG', isStraight: true },
    { src: '/bridal_bouquet/11.JPG', isStraight: true },
    { src: '/bridal_bouquet/12.JPG', isStraight: true },
    { src: '/bridal_bouquet/13.JPG', isStraight: true },
    { src: '/bridal_bouquet/14.JPG', isStraight: false },
    { src: '/bridal_bouquet/15.JPEG', isStraight: false },
    { src: '/bridal_bouquet/16.JPG', isStraight: false },
    { src: '/bridal_bouquet/17.JPG', isStraight: false },
    { src: '/bridal_bouquet/18.JPG', isStraight: false },
    { src: '/bridal_bouquet/IMG_6565.JPG', isStraight: false },
    { src: '/bridal_bouquet/IMG_6825.JPG', isStraight: false },
    { src: '/bridal_bouquet/IMG_8673.JPG', isStraight: true },
    { src: '/bridal_bouquet/IMG_8673_2.JPG', isStraight: false },
  ],
  floral_bouquet: [
    { src: '/floral_bouquet/01.JPG', isStraight: false },
    { src: '/floral_bouquet/02.JPG', isStraight: false },
    { src: '/floral_bouquet/03.JPG', isStraight: false },
    { src: '/floral_bouquet/04.JPG', isStraight: false },
    { src: '/floral_bouquet/08.JPG', isStraight: true },
    { src: '/floral_bouquet/10.JPG', isStraight: false },
    { src: '/floral_bouquet/11.JPG', isStraight: false },
    { src: '/floral_bouquet/12.JPG', isStraight: false },
    { src: '/floral_bouquet/13.JPG', isStraight: false },
    { src: '/floral_bouquet/15.JPG', isStraight: true },
    { src: '/floral_bouquet/19.JPG', isStraight: true },
    { src: '/floral_bouquet/20.JPG', isStraight: false },
    { src: '/floral_bouquet/21.JPG', isStraight: false },
    { src: '/floral_bouquet/22.JPG', isStraight: false },
    { src: '/floral_bouquet/25.JPG', isStraight: true },
    { src: '/floral_bouquet/26.JPG', isStraight: true },
    { src: '/floral_bouquet/百子蓮.JPG', isStraight: true },
    { src: '/floral_bouquet/百子蓮(1).JPG', isStraight: false },
    { src: '/floral_bouquet/百子蓮(2).JPG', isStraight: false },
    { src: '/floral_bouquet/流沙玫瑰花束.JPG', isStraight: false },
    { src: '/floral_bouquet/流沙玫瑰花束(1).JPG', isStraight: true },
    { src: '/floral_bouquet/流沙玫瑰花束(2).JPG', isStraight: false },
    { src: '/floral_bouquet/流沙玫瑰花束(3).JPG', isStraight: false },
    { src: '/floral_bouquet/單枝花束永生玫瑰.JPG', isStraight: false },
    { src: '/floral_bouquet/滿天星花束.JPG', isStraight: false },
    { src: '/floral_bouquet/滿天星花束.JPEG', isStraight: false },
    { src: '/floral_bouquet/滿天星花束(1).JPG', isStraight: true },
    { src: '/floral_bouquet/滿天星花束(2).JPG', isStraight: true },
    { src: '/floral_bouquet/滿天星花束(3).JPG', isStraight: false },
    { src: '/floral_bouquet/滿天星花束(4).JPG', isStraight: false },
  ],
  floral_box: [
    { src: '/floral_box/1.JPG', isStraight: true },
    { src: '/floral_box/花時計1.JPG', isStraight: false },
    { src: '/floral_box/花時計2.JPG', isStraight: false },
    { src: '/floral_box/花時計3.JPG', isStraight: false },
    { src: '/floral_box/花盒.JPG', isStraight: false },
    { src: '/floral_box/花盒(1).JPG', isStraight: false },
    { src: '/floral_box/花盒(2).JPG', isStraight: false },
    { src: '/floral_box/玻璃盅.JPG', isStraight: true },
    { src: '/floral_box/玻璃盅(1).JPG', isStraight: false },
    { src: '/floral_box/玻璃盅(2).JPG', isStraight: true },
    { src: '/floral_box/玻璃盅(3).JPG', isStraight: true },
    { src: '/floral_box/玻璃盅(4).JPG', isStraight: false },
    { src: '/floral_box/玻璃盅(5).JPG', isStraight: true },
    { src: '/floral_box/玻璃盅(6).JPG', isStraight: false },
    { src: '/floral_box/酒花.JPG', isStraight: false },
    { src: '/floral_box/酒花(1).JPG', isStraight: true },
    { src: '/floral_box/酒花(2).JPG', isStraight: false },
    { src: '/floral_box/開幕永生盆.JPG', isStraight: false },
    { src: '/floral_box/開幕永生盆花.JPG', isStraight: false },
    { src: '/floral_box/燈籠花禮.JPG', isStraight: false },
    { src: '/floral_box/燈籠花禮(1).JPG', isStraight: true },
  ],
  wedding_decor: [
    { src: '/wedding_decor/5E88A202-26AE-45AB-A5DD-48F9C0C5EF6C.JPG', isStraight: true },
    { src: '/wedding_decor/7E8D2299-7727-444F-94B6-E8C0F5F98B61.JPG', isStraight: false },
    { src: '/wedding_decor/19E94C4F-AFE1-4FCD-AE9D-A66BF76DC612.JPG', isStraight: true },
    { src: '/wedding_decor/791EBEDD-327F-4A08-82B6-BED877F3F1C4.JPG', isStraight: false },
    { src: '/wedding_decor/A3A5F5C4-F4E6-4B5F-A210-DA03AD00B0C7.JPG', isStraight: false },
    { src: '/wedding_decor/EC9C0E57-1211-4EA2-AE99-8D8CBFD4FDBD.JPG', isStraight: false },
    { src: '/wedding_decor/IMG_8728.JPG', isStraight: false },
    { src: '/wedding_decor/IMG_8729.JPG', isStraight: false },
  ],
  wreath: [
    { src: '/wreath/068669D6-D43F-40F7-8F78-B8C375804B02.JPG', isStraight: false },
    { src: '/wreath/花冠頭飾.JPG', isStraight: false },
    { src: '/wreath/花冠頭飾(1).JPG', isStraight: false },
    { src: '/wreath/花冠頭飾(2).JPG', isStraight: false },
    { src: '/wreath/花冠頭飾1.JPG', isStraight: false },
    { src: '/wreath/乾燥小花圈.JPG', isStraight: false },
    { src: '/wreath/乾燥小花圈(1).JPG', isStraight: false },
    { src: '/wreath/BA40D9DE-F74F-45D4-AB44-781FB0DD387D.JPG', isStraight: false },
  ],
}
