export default {
  bridal_bouquet: [
    {
      src: '/bridal_bouquet/792A809C-81D7-4264-B7DC-CD5718A62A21-1967-000000DA63A3A659.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/bridal_bouquet/846A32C4-952C-4881-927F-1D110DEA0B2E-1895-00000166D1670ECA.jpg',
      isStraight: true,
      type: 'middle',
    },
    { src: '/bridal_bouquet/19.JPG', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/000.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/001.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/002.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/003.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/004.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/005.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/006.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/007.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/008.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/009.png', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/011.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/010.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/012.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/006-1.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/013.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/014.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/015.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/016.png', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/018.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/020.png', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/021.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/022.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/019.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/023.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/024.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/026.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/025.png', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/027.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/028.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/029.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/030.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/031.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/032.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/033.png', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/034.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/035.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/09BD6710-B0F8-4B66-8B80-36CD0DF6128B.png', isStraight: true, type: 'middle' },
    {
      src: '/bridal_bouquet/1D1B86DC-B6D5-403E-9E25-74D497984326-6E47E992-7F2D-4503-886B-8F2FC184C541.png',
      isStraight: false,
      type: 'large',
    },
    {
      src: '/bridal_bouquet/23485F16-92FC-4B43-8E36-7D3C4CE4CD3F-2BAA3A55-E8ED-4734-89BF-C52E3C824B75.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/bridal_bouquet/24A9C463-844B-4C24-8CC2-76A1F90CADFF-9FCA007D-047F-4972-BCE0-3A02C2A47FB1.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/bridal_bouquet/290BDBF5-DB98-4FE9-BC7F-6A834420E502-267DB271-0E32-43D6-9E98-2A358A0967CD.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/bridal_bouquet/69F4F892-CE1C-415D-ADA9-1777B3E0EFB5-81AE60DC-0460-473E-8C66-945BD19BFC4A.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/bridal_bouquet/48D4C708-56D7-4FB6-8D8F-21191A3E7732-9955FADA-3731-400D-9390-7A939A007B19.png',
      isStraight: false,
      type: 'small',
    },
    {
      src: '/bridal_bouquet/509B576D-9F1F-4A87-BF9A-CC83F1496419-0D9D0568-C5AE-4EC6-9FEE-FC7B5C7B425E.png',
      isStraight: false,
      type: 'small',
    },
    {
      src: '/bridal_bouquet/897F5750-0A8A-4FD8-8241-7C87886D6DEC-D941A4D8-6B10-4462-8F0B-5A3B133FE61A.png',
      isStraight: false,
      type: 'small',
    },
    {
      src: '/bridal_bouquet/89D0B589-BE23-416B-925D-517B10851D08-7B0E10CF-A3D2-44D8-BC63-E9C3F80CC127.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/bridal_bouquet/983427D6-266B-4D87-89DF-241B3984E640-436F6F55-224C-4225-B33B-93EDA3C9426D.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/bridal_bouquet/8D56CAFC-768D-4603-8D8E-ADEE8F4CCC31-06A1A41A-414A-41C7-AF9E-5987518212C9.png',
      isStraight: false,
      type: 'small',
    },
    { src: '/bridal_bouquet/036.png', isStraight: false, type: 'small' },
    {
      src: '/bridal_bouquet/C322391A-6C83-447B-B884-5AB618325DBF-8D669DC2-165E-427D-83E9-574F55876445.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/bridal_bouquet/ABC9276D-1BFF-478B-9D41-38E8CF903993-9B3F54F4-9186-4922-91C2-4FFEFD1729DE.png',
      isStraight: false,
      type: 'small',
    },
    {
      src: '/bridal_bouquet/AFB16CAB-14DD-459B-8CEE-C84E83A6B43A-A001579C-0F18-4479-BA9D-591590478511.png',
      isStraight: false,
      type: 'small',
    },
    {
      src: '/bridal_bouquet/E3403718-D39B-420D-8A4C-224123F0E672-288B6FD8-3418-4D71-A0C7-37C9BFA59175.png',
      isStraight: false,
      type: 'small',
    },
    { src: '/bridal_bouquet/24.jpg', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/IMG_2287.png', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/20.jpg', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/33.jpg', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/22.jpg', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/28.jpg', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/23.jpg', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/21.jpg', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/25.jpg', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/26.jpg', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/27.jpg', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/31.jpg', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/32.jpg', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/29.jpg', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/1.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/3.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/4.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/6.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/2.JPG', isStraight: false, type: 'middle' },
    { src: '/bridal_bouquet/5.JPG', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/8.JPG', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/10.JPG', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/11.JPG', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/12.JPG', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/7.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/9.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/14.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/15.JPEG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/16.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/18.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/IMG_6565.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/IMG_6825.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/13.JPG', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/17.JPG', isStraight: false, type: 'large' },
    { src: '/bridal_bouquet/IMG_8673.JPG', isStraight: true, type: 'middle' },
    { src: '/bridal_bouquet/IMG_8673_2.JPG', isStraight: false, type: 'small' },
    { src: '/bridal_bouquet/30.jpg', isStraight: false, type: 'small' },
  ],
  floral_bouquet: [
    {
      src: '/floral_bouquet/04BC766A-726C-4710-BCCB-15CE2817FF05-1573-000000F5CF135062.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/BF31933B-C4D7-4CFA-87E7-2B77B88C59DC-1027-000000D9C5EBE859.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/EC9BF95E-DDFF-4F4D-8719-E743D6C54E5D-3448-000002215B5B6D9A.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/F1923B44-E3A0-45A5-8041-FBFC9C01F8B0-3479-0000021468DF83F3.jpg',
      isStraight: true,
      type: 'middle',
    },
    { src: '/floral_bouquet/IMG_5827-min.png', isStraight: true, type: 'middle' },
    {
      src: '/floral_bouquet/3BEE94E9-12FE-46A4-B8DF-07F4671FD771-593-000000376F888BD6.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/85DBBB19-6A0C-4E37-A59A-371597672B0C-6553-000003A339B60C05.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/307DED42-312E-4FC3-9305-5C9F2F72D67C-1573-000000F5C421A1DE.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/1475C182-4681-4B2E-8501-FFEDAFDC97E9-1573-000000F5C96D8CF8.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/A4FBA1B7-D0C6-49D6-9D6C-3C35AFB1C66E-3448-0000022153D1EA5A.jpg',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/FEEF1F3D-3CB2-44FC-B80C-D0081E98EBE4-1573-000000F5C6F8E9C5.jpg',
      isStraight: true,
      type: 'middle',
    },
    { src: '/floral_bouquet/File_000.png', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/File_001.png', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/File_002.png', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/File_003.jpeg', isStraight: true, type: 'middle' },
    {
      src: '/floral_bouquet/5D4D899D-772B-469A-B8BE-B723B2FCD43A-1027-000000D9BDD06374.jpg',
      isStraight: false,
      type: 'large',
    },
    { src: '/floral_bouquet/File_005.jpeg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/File_004.png', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/File_006.png', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/單枝花束永生玫瑰.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/File_007.png', isStraight: false, type: 'large' },
    { src: '/floral_bouquet/File_008.png', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/File_009.png', isStraight: true, type: 'middle' },
    {
      src: '/floral_bouquet/9237C551-25E6-4089-BB15-267064B88747-D026E362-28DC-41C7-8681-8F1C397F6645.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/CFC7E7E1-C4D9-45E1-990E-48B19BD1455E-8029E9F9-4D82-47FB-8C0B-612E5F6E2E30.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/996C3024-405B-416C-85E2-DC396B3B0267-581562F8-DCB7-4C93-8C32-2F52C1AD0AAC.png',
      isStraight: true,
      type: 'middle',
    },
    {
      src: '/floral_bouquet/42453C47-2CAB-432E-92A5-BD5EB742E0EF-CB6F687C-FB70-407A-8186-B7E847F7AC8F.png',
      isStraight: false,
      type: 'large',
    },
    { src: '/floral_bouquet/28.jpg', isStraight: false, type: 'large' },
    { src: '/floral_bouquet/27.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/29.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/30.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/31.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/32.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/33.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/34.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/35.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/36.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/37.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/40.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/42.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/41.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/38.jpg', isStraight: false, type: 'large' },
    { src: '/floral_bouquet/43.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/39.jpg', isStraight: false, type: 'large' },
    { src: '/floral_bouquet/01.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/02.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/08.JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/03.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/04.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/10.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/13.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/15.JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/25.JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/19.JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/11.JPG', isStraight: false, type: 'large' },
    { src: '/floral_bouquet/20.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/12.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/百子蓮(1).JPG', isStraight: false, type: 'large' },
    { src: '/floral_bouquet/百子蓮.JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/21.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/22.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/百子蓮(2).JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/26.JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/流沙玫瑰花束(1).JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/流沙玫瑰花束.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/流沙玫瑰花束(2).JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/流沙玫瑰花束(3).JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/滿天星花束.JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/滿天星花束.JPEG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/滿天星花束(1).JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/滿天星花束(2).JPG', isStraight: true, type: 'middle' },
    { src: '/floral_bouquet/滿天星花束(3).JPG', isStraight: false, type: 'small' },
    { src: '/floral_bouquet/滿天星花束(4).JPG', isStraight: false, type: 'small' },
  ],
  floral_box: [
    { src: '/floral_box/File_000.png', isStraight: false, type: 'large' },
    { src: '/floral_box/File_001.png', isStraight: true, type: 'middle' },
    { src: '/floral_box/File_002.png', isStraight: true, type: 'middle' },
    { src: '/floral_box/File_004.png', isStraight: false, type: 'large' },
    { src: '/floral_box/File_003.png', isStraight: true, type: 'middle' },
    { src: '/floral_box/花時計1.JPG', isStraight: false, type: 'small' },
    { src: '/floral_box/花時計3.JPG', isStraight: false, type: 'small' },
    { src: '/floral_box/花盒.JPG', isStraight: false, type: 'small' },
    { src: '/floral_box/花盒(2).JPG', isStraight: false, type: 'small' },
    { src: '/floral_box/花盒(1).JPG', isStraight: false, type: 'large' },
    { src: '/floral_box/玻璃盅.JPG', isStraight: true, type: 'middle' },
    { src: '/floral_box/玻璃盅(2).JPG', isStraight: true, type: 'middle' },
    { src: '/floral_box/玻璃盅(3).JPG', isStraight: true, type: 'middle' },
    { src: '/floral_box/玻璃盅(5).JPG', isStraight: true, type: 'middle' },
    { src: '/floral_box/酒花.JPG', isStraight: false, type: 'large' },
    { src: '/floral_box/玻璃盅(6).JPG', isStraight: false, type: 'small' },
    { src: '/floral_box/玻璃盅(4).JPG', isStraight: false, type: 'small' },
    { src: '/floral_box/酒花(2).JPG', isStraight: false, type: 'large' },
    { src: '/floral_box/酒花(1).JPG', isStraight: true, type: 'middle' },
    { src: '/floral_box/燈籠花禮(1).JPG', isStraight: true, type: 'middle' },
    { src: '/floral_box/燈籠花禮.JPG', isStraight: false, type: 'large' },
    { src: '/floral_box/4.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_box/55.jpg', isStraight: true, type: 'middle' },
    { src: '/floral_box/開幕永生盆花.JPG', isStraight: false, type: 'small' },
    { src: '/floral_box/開幕永生盆.JPG', isStraight: false, type: 'small' },
    { src: '/floral_box/3.jpg', isStraight: false, type: 'large' },
    { src: '/floral_box/2.jpg', isStraight: false, type: 'small' },
    { src: '/floral_box/玻璃盅(1).JPG', isStraight: false, type: 'small' },
  ],
  wedding_decor: [
    { src: '/wedding_decor/File_000.png', isStraight: false, type: 'large' },
    { src: '/wedding_decor/File_002.png', isStraight: true, type: 'middle' },
    { src: '/wedding_decor/File_001.png', isStraight: false, type: 'large' },
    { src: '/wedding_decor/File_003.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/File_004.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/File_005.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/File_006.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/File_009.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/File_007.png', isStraight: true, type: 'middle' },
    { src: '/wedding_decor/File_008.png', isStraight: true, type: 'middle' },
    { src: '/wedding_decor/File_010.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/File_012.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/File_011.png', isStraight: false, type: 'large' },
    { src: '/wedding_decor/File_013.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/File_014.png', isStraight: false, type: 'small' },
    { src: '/wedding_decor/5E88A202-26AE-45AB-A5DD-48F9C0C5EF6C.JPG', isStraight: true, type: 'middle' },
    { src: '/wedding_decor/19E94C4F-AFE1-4FCD-AE9D-A66BF76DC612.JPG', isStraight: true, type: 'middle' },
    { src: '/wedding_decor/7E8D2299-7727-444F-94B6-E8C0F5F98B61.JPG', isStraight: false, type: 'small' },
    { src: '/wedding_decor/A3A5F5C4-F4E6-4B5F-A210-DA03AD00B0C7.JPG', isStraight: false, type: 'small' },
    { src: '/wedding_decor/791EBEDD-327F-4A08-82B6-BED877F3F1C4.JPG', isStraight: false, type: 'large' },
    { src: '/wedding_decor/EC9C0E57-1211-4EA2-AE99-8D8CBFD4FDBD.JPG', isStraight: false, type: 'small' },
    { src: '/wedding_decor/IMG_8728.JPG', isStraight: false, type: 'small' },
    { src: '/wedding_decor/IMG_8729.JPG', isStraight: false, type: 'small' },
  ],
  wreath: [
    {
      src: '/wreath/48D4C708-56D7-4FB6-8D8F-21191A3E7732-9955FADA-3731-400D-9390-7A939A007B19.jpg',
      isStraight: false,
      type: 'large',
    },
    { src: '/wreath/089D6415-CF7F-4642-9BD8-C2B0EC13752D-1303-000000F9548851FB.jpg', isStraight: false, type: 'small' },
    {
      src: '/wreath/897F5750-0A8A-4FD8-8241-7C87886D6DEC-D941A4D8-6B10-4462-8F0B-5A3B133FE61A.jpg',
      isStraight: false,
      type: 'small',
    },
    { src: '/wreath/B935B2A3-71A8-4F86-A992-AE205079DB11-1303-000000F9585F514E.jpg', isStraight: false, type: 'small' },
    {
      src: '/wreath/BF2EA1FA-1B66-4876-AB23-D9F0EE8FAF5B-6B744595-8337-469E-8773-4A888D2A7D85.jpg',
      isStraight: false,
      type: 'small',
    },
    {
      src: '/wreath/CF39D20B-CB40-48CB-8F1F-FD8DB2132822-1303-000000F95E5B2B69.jpg',
      isStraight: false,
      type: 'small',
    },
    { src: '/wreath/File_000.png', isStraight: false, type: 'large' },
    { src: '/wreath/File_003.png', isStraight: true, type: 'middle' },
    { src: '/wreath/File_004.png', isStraight: true, type: 'middle' },
    { src: '/wreath/File_006.png', isStraight: true, type: 'middle' },
    { src: '/wreath/File_001.png', isStraight: false, type: 'small' },
    { src: '/wreath/File_002.png', isStraight: false, type: 'small' },
    { src: '/wreath/File_007.png', isStraight: true, type: 'middle' },
    { src: '/wreath/068669D6-D43F-40F7-8F78-B8C375804B02.JPG', isStraight: true, type: 'middle' },
    { src: '/wreath/File_005.png', isStraight: false, type: 'small' },
    { src: '/wreath/花冠頭飾.JPG', isStraight: false, type: 'small' },
    { src: '/wreath/花冠頭飾(1).JPG', isStraight: false, type: 'small' },
    { src: '/wreath/花冠頭飾(2).JPG', isStraight: false, type: 'small' },
    { src: '/wreath/花冠頭飾1.JPG', isStraight: false, type: 'small' },
    { src: '/wreath/乾燥小花圈(1).JPG', isStraight: false, type: 'large' },
    { src: '/wreath/BA40D9DE-F74F-45D4-AB44-781FB0DD387D.JPG', isStraight: true, type: 'middle' },
    { src: '/wreath/乾燥小花圈.JPG', isStraight: false, type: 'small' },
  ],
}
